name: Publish to AUR

on:
  release:
    types: [created, published]

jobs:
  publish-aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Update PKGBUILD version
        run: |
          sed -i "s/pkgver=.*/pkgver=$VERSION/" PKGBUILD
          
      - name: Calculate checksums
        run: |
          # Download the source archive
          SOURCE_URL="https://github.com/streek/go-weather/archive/v$VERSION.tar.gz"
          curl -L -o source.tar.gz $SOURCE_URL
          SHA256=$(sha256sum source.tar.gz | awk '{print $1}')
          
          # Extract to see actual directory name
          tar -tf source.tar.gz | head -1 | cut -d'/' -f1 > extracted_dir.txt
          EXTRACTED_DIR=$(cat extracted_dir.txt)
          
          # Update PKGBUILD with correct checksum and source directory
          sed -i "s/sha256sums=('SKIP')/sha256sums=('$SHA256')/" PKGBUILD
          
          # Update PKGBUILD to use correct directory name in build() and package()
          sed -i "s/go-weather-\$pkgver/$EXTRACTED_DIR/g" PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: wgo
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version ${{ env.VERSION }}"
          allow_empty_commits: false
